# Import Libaries

In [7]:
import kagglehub
import pandas as pd

from pathlib import Path

# 0. Load Data

In [5]:
path = kagglehub.dataset_download(
    "sriharshabsprasad/movielens-dataset-100k-ratings",
    output_dir="data"
)

DATA_PATH = Path(path) / "ml-latest-small"

print("Path to dataset files:", DATA_PATH)

Path to dataset files: data\ml-latest-small

# 1. Data Inspection

## Create paths and dataframes

In [9]:
LINK_PATH = DATA_PATH / "links.csv"
MOVIES_PATH = DATA_PATH / "movies.csv"
RATINGS_PATH = DATA_PATH / "ratings.csv"
TAGS_PATH = DATA_PATH / "tags.csv"

links = pd.read_csv(LINK_PATH)
movies = pd.read_csv(MOVIES_PATH)
ratings = pd.read_csv(RATINGS_PATH)
tags = pd.read_csv(TAGS_PATH)

print("Links path:", LINK_PATH)
print("Movies path:", MOVIES_PATH)
print("Ratings path:", RATINGS_PATH)
print("Tags path:", TAGS_PATH)

Links path: data\ml-latest-small\links.csv
Movies path: data\ml-latest-small\movies.csv
Ratings path: data\ml-latest-small\ratings.csv
Tags path: data\ml-latest-small\tags.csv

## Inspect files

In [12]:
print("Links shape:", links.shape)
print("Movies shape:", movies.shape)
print("Ratings shape:", ratings.shape)
print("Tags shape:", tags.shape)

Links shape: (9742, 3)
Movies shape: (9742, 3)
Ratings shape: (100836, 4)
Tags shape: (3683, 4)

In [14]:
display(links.head())
display(movies.head())
display(ratings.head())
display(tags.head())

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

### Info
The most important file in this dataset is **`ratings.csv`**, as it contains information about users, movies, and their ratings. We will mainly use this file to build our recommendation system.