# Import Libaries

In [1]:
import kagglehub
import pandas as pd

from pathlib import Path

# 0. Load data

In [7]:
path = kagglehub.dataset_download(
    "aslanahmedov/walmart-sales-forecast",
    output_dir="data"
)

DATA_DIR = Path(path)

FEATURES_DIR = DATA_DIR / "features.csv"
STORES_DIR = DATA_DIR / "stores.csv"
TEST_DIR = DATA_DIR / "test.csv"
TRAIN_DIR = DATA_DIR / "train.csv"

print("Path to features dataset files:", FEATURES_DIR)
print("Path to stores dataset files:", STORES_DIR)
print("Path to test dataset files:", TEST_DIR)
print("Path to train dataset files:", TRAIN_DIR)

Path to features dataset files: data\features.csv
Path to stores dataset files: data\stores.csv
Path to test dataset files: data\test.csv
Path to train dataset files: data\train.csv

# 1. Data inspection

In [26]:
features_df = pd.read_csv(FEATURES_DIR)
stores_df = pd.read_csv(STORES_DIR)
test_df = pd.read_csv(TEST_DIR)
train_df = pd.read_csv(TRAIN_DIR)

data_frames = {
    "features": features_df,
    "stores": stores_df,
    "test": test_df,
    "train": train_df
}

for name, df in data_frames.items():
    print("Data:", name.capitalize())
    print("Shape:", df.shape)
    print("Columns", list(df.columns))
    display(df.head(1))
    print()

Data: Features
Shape: (8190, 12)
Columns ['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment', 'IsHoliday']

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False

Data: Stores
Shape: (45, 3)
Columns ['Store', 'Type', 'Size']

   Store Type    Size
0      1    A  151315

Data: Test
Shape: (115064, 4)
Columns ['Store', 'Dept', 'Date', 'IsHoliday']

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False

Data: Train
Shape: (421570, 5)
Columns ['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday']

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05       24924.5      False

### Info
The dataset consists of four smaller datasets: `Features`, `Stores`, `Train`, and `Test`.
The `Features` dataset contains weekly information about each store, including **Temperature**, **Fuel Price**, **CPI**, **Unemployment**, **MarkDowns**, and holiday information.
The `Stores` dataset identifies each store and provides additional information such as its **Type** and **Size**.
The `Train` and `Test` datasets contain the main forecasting data, including **Store**, **Department**, **Date**, and **IsHoliday**. The `Train` dataset also contains the target variable, **Weekly_Sales**, which we will use to train the forecasting model.